import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import Navbar from "../components/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Image Locator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <Navbar />
        <body className={inter.className}>{children}</body>
    </html>
  );
}
